apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patroni.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patroni.labels" . | nindent 4 }}
type: Opaque
stringData:
  PATRONI_SUPERUSER_USERNAME: {{ .Values.postgresql.username | quote }}
  PATRONI_SUPERUSER_PASSWORD: {{ .Values.postgresql.password | default (randAlphaNum 16) | quote }}
  PATRONI_REPLICATION_USERNAME: {{ .Values.postgresql.replicationUsername | quote }}
  PATRONI_REPLICATION_PASSWORD: {{ .Values.postgresql.replicationPassword | default (randAlphaNum 16) | quote }}
